import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ActivityCreate {
  @ApiProperty()
  customer_id: string;
  @ApiProperty()
  type: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  scheduled_at: Date;
}

export class Activity {
  @ApiProperty()
  id: number;
  @ApiProperty()
  customer_id: string;
  @ApiProperty()
  type: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  scheduled_at: Date;
}
